version: '2.3'

services:
  dev:
    working_dir: /app
    command: /bin/bash
    # image: paulasquin/dev:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev

    # Shared volumes among Docker container and host machine
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.aws:/root/.aws
      - ${HOME}.docker:/root/.docker
    
    env_file:
      - .env
      
    
